### ISSUE TITLE
Identities not visible in client in after boot Windows 11

### ISSUE THREAD

**Issue by samsoeapp** [openziti/desktop-edge-win#715] opened 2024-08-02 07:15 UTC
Hi,

I have noticed on multiple of our workstations that when we boot into Windows 11, after the desktop-edge-win application started no identity's show. This sometimes persist even after rebooting the machine. For now, we don't start the application on boot, but just manually starting it when it is needed because it sometimes has the intention of adding all routes into the windows machine while the identity is not active at that time, resulting in not being able to make the necessary connections.

So, to summarize the only 2 issues we are experiencing at the moment:
- No identity's visible in UI after start. (Even if before shutting down they were available)
- Sometimes when disabling identity's, the routes of that identity persist in windows 11

Steps to (mostly of the times) fix the issue. (On boot, when at previous shutdown everything was working fine)
- Close the desktop-edge-win application trough the UI
- Open services.msc and stop the "Ziti Desktop Monitor Service" ("Ziti Desktop Edge Service" is already stopped at this moment of time)
- Open the desktop-edge-win and hope for the best!

This issue is not the end of the world, but for some less technical colleagues it brings a lot of extra work. Because as you can expect they will try to reinstall the desktop-edge-win and thus needing new files to get the identity back into the application.

We are currently running version:
App: 2.4.0.0
Service: v1.0.7@

Before this we were running:
2.3.1 (https://github.com/openziti/desktop-edge-win/releases/tag/2.3.1)

I have to add, that when upgrading to 2.4.0.0, the issue of the application not cleaning up routes after disabling identity are not happening that often. Also, I want to add that in my work i have to deal with a lot of disconnections and changes in network on my laptop due to the fact I mostly replace firewalls, switches etc.

**Comment by dovholuknf** [comment] 2024-08-02 12:16
You should never need to perform these steps. To me, this is indicating some kind of bug that needs to be found and squashed. Personally, I've never seen the "no identities" thing you're reporting assuming the `ziti` service is running.

For one of those workstations can you send me the logs to look at? Either email or discourse or via some link. (help at openziti.org)

I really don't recommend not starting the services on start, but -- that's your prerogative for sure! :) There are two services that ship with ZDEW:
* Ziti Desktop Edge Service. This is the service that must be running to see identities and to have data flow. start stop using: `net stop/start ziti`
* Ziti Desktop Monitor Service. This service starts/stops the `ziti` service for non-administrator users and performs the automatic upgrade functionality as well as the log collection task. If this task is not running, users won't get upgrades and won't be able to start/stop the `ziti` process from the UI. start stop using: `net stop/start ziti-monitor`

When you disable an identity, I do expect routes to clean up. If they aren't, I'd consider that a bug too that should be fixed.

If closing the UI and opening it back up fixes the problem, that indicates to me that it's hung up. It might be due to starting the UI without having the `ziti` service running and since it sounds inconsistent, it might be a race condition of some flavor. If you have easy steps to reproduce that'd be appreciated.

When you open the UI and go to "Feedback" a zip file gets generated (if interested you can generate one or [look at the code for it here](https://github.com/openziti/desktop-edge-win/blob/4cb30d125f5fb0400e5bfc69132776164efaff5d/ZitiUpdateService/UpdateService.cs#L311C1-L319C37)). Generally speaking I usually can see what i need by looking at the logs collected. It would be best if you enabled DEBUG logging before collecting and sending me the logs.

**Comment by samsoeapp** [comment] 2024-08-07 07:03
Goodmorning @dovholuknf ,

I just booted my laptop and ziti is showing no identity's.

Both services are running but this is how the client looks:
![image](https://github.com/user-attachments/assets/edceec6b-0968-43be-bf95-810374c0bfe9)
![image](https://github.com/user-attachments/assets/6c3c63d8-25e7-44f3-b94a-8ca1be83fbf1)

I followed the following steps:
1. Set the logging level to debug.
2. Closing the UI
3. Opening the UI (Still no identity's)
4. Running the feedback button

I still have to do a simple reboot, which I want to check if this resolves the issue. 
I'll share the outcome of this in a new comment.

I'll send u the logs, though it took a while to create them.
Hopefully there is some useful information available in it!

**Comment by samsoeapp** [comment] 2024-08-07 09:45
@dovholuknf 

After a reboot the UI started successfully, and my identities returned.
I was unable to create logs also before the reboot so I created them after the reboot using the feedback option.

How should i send the zip package to you?

**Comment by dovholuknf** [comment] 2024-12-19 20:29
i'm sorry i somehow missed this comment! my bad. please use discourse for support-related requests. I get (and miss) a lot of github notifcations sometimes. sorry. given the age, i'm closing this issue. open it again if needed.

**Closed by dovholuknf** 2024-12-19 20:29 UTC
