### ISSUE TITLE
After Patch Start

### ISSUE THREAD

**Issue by runfreeproject** [openziti/desktop-edge-win#740] opened 2024-10-21 11:46 UTC
I know this will be a difficult bug to chase but I have noticed after a round of patching servers that Ziti does not start on reboot after a Windows patch when you get stuck in that sort of "Hey, Windows was just updated!" startup screen. I have needed to make sure I had some IP firewall rule as backup to get in via RDP to allow Ziti to start up. This may be a services in general but thought I would make a note of it to see if there was a way to set the service to run regardless of this state.

**Comment by dovholuknf** [comment] 2024-10-21 11:59
Can you share the logs from the event? Did you capture a feedback.zip and can you send them along?

This behavior is not expected. The only time I've seen anything remotely similar to this was on a full windows upgrade/replace where Windows will take your entire Windows directory and move it to a "backup" location (such as c:\windows.old).

I'd also like to know if the event viewer had any errors in the application/system logs that seem "ziti adjacent"

**Comment by dovholuknf** [comment] 2024-12-19 20:22
closing - talked to user. this was caused by controller PKI related issues.

**Closed by dovholuknf** 2024-12-19 20:22 UTC
